### ISSUE TITLE
Add references to the canonical instances of the conditional tokens contracts

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-docs#19]
The docs do not make it immediately obvious that the CTF is intended to be a singleton contract, which has resulted in people deploying their own instances of the contracts.

We should make sure to:
1. Make it explicit that there is no need to deploy your own instance
2. Make it easy to find the address for the CTF contracts on mainnet (along with any testnets where it is deployed)

The addresses can be found here:
https://github.com/gnosis/conditional-tokens-contracts/blob/master/networks.json

Mainnet: `0xC59b0e4De5F1248C1140964E0fF287B192407E0C`
Rinkeby: `0x36bede640D19981A82090519bC1626249984c908`

**Comment by Graeme-Code** [comment]
Agree. 

But how? In the very least this should be communicated on: https://conditionaltokens-docs.dev.gnosisdev.com/conditionaltokens/docs/devguide01/

But if the goal is that it's understood that there is only a need for one instance of the CT framework contract it should prob be front and centre here: https://conditionaltokens-docs.dev.gnosisdev.com/conditionaltokens/

Efforts to support this, we have Alan's screencast(soon) on how to interact with CT framework on Rinkeby.
